from django.db import models


# Create your models here.

# class Order(models.Model):
#     user_id = ...
#     first_name = ...
#     last_name = ...
#
#     postal_code = ...
#     city = ...
#     street = ...
#     building_number = ...
#     apartment_number = ...
#
#     created_datetime = ...
#     updated_datetime = ...
#     status = ...


# class OrderItem(models.Model):
#     ...
